import localFont from 'next/font/local';
// import './style.css';
import { AnimatePresence, motion } from 'framer-motion';
import BackgroundProvider from '@/app/protected/test/context';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: '스마트 부표 바이오파울링 탐지 서비스',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <BackgroundProvider>{children}</BackgroundProvider>
      </body>
    </html>
  );
}
